### ISSUE TITLE
Submitting LaunchpadScriptV3 to Bitwig's controller pages

### ISSUE THREAD

**Issue by gitanat** [dplduffy/LaunchpadScriptV3#4]
Hi @dplduffy 
Thanks for putting this together, it's a big improvement over Edward's version.
Are you planning on submitting it to [Bitwig's controllers page](https://www.bitwig.com/en/community/control_scripts.html)? I think it would lead to more people using it (I only found it by accident!)

**Comment by dplduffy** [comment]
Hey no problem glad you’re using it.

I’m not planning on submitting it for a few reasons. 1. Because I don’t own
a launchpad or Bitwig anymore so I won’t be supporting it, and 2. Because
moss’ scripts are so much better.  If you haven’t seen them check out the
DrivenByMoss bitwig scripts.

-Dan

**Comment by gitanat** [comment]
Thanks for the quick response!
I've seen DrivenByMoss', but didn't try it yet - thanks for the tip!
